### ISSUE TITLE
Texture2DArray is too large; only support up to 2GB sizes

### ISSUE THREAD

**Issue by FilipeLopesPires** [keijiro/SlitScanCam#3]
Hello @keijiro ,

First of all, thank you for freely sharing this code, I have been looking for something like this for a while and only found offline solutions. I have tested yours and it works fine in real-time, both in Windows and in Android.

I have tweaked a bit on the SlitScanCam script and found that I can increase the image size of the 2D Texture to 1920x1080, but when I increase the resolution from 256 to (for example) 512, it raises the following error:

```
Texture2DArray is too large; only support up to 2GB sizes UnityEngine.Texture2DArray:.ctor(Int32, Int32, Int32, TextureFormat, Boolean)
UnityException: Failed to create 2D array texture because of invalid parameters.
(...)
```

Is there a way to overcome this limitation?
Thank you for your attention!

**Comment by keijiro** [comment]
There is no easy solution. You have to split the texture array into multiple arrays.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
